# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Spreadsheet-SimpleExcel
version:      0.02
version_from: lib/Spreadsheet/SimpleExcel.pm
installdirs:  site
requires:
    Spreadsheet::WriteExcel:       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
